spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mow_backend
    username: root
    password: kim122101
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update

security:
  user:
    name: test
    password: test

mow:
  auth:
    tokenSecret: kYp3s6v9y/B?E(H+MbQeThWmZq4t7w!z%C*F)J@NcRfUjXn2r5u8x/A?D(G+KaPd
    tokenExpirationMsec: 86400000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
